services:
    core.factory.entity:
        class: CoreBundle\Factory\EntityFactory

    auth.service.token:
        class: CoreBundle\Service\TokenService
        arguments: ['@doctrine.orm.entity_manager', '@core.factory.entity']

    auth.provider.user:
        class: CoreBundle\Service\ApiKeyUserProvider
        arguments: ['@doctrine.orm.entity_manager', '@core.factory.entity']

    auth.authenticator:
        class: CoreBundle\Authenticator\ApiKeyAuthenticator
        public: false

    security.access_listener:
        class: CoreBundle\EventListner\AccessListner
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage', '@auth.service.token', '@core.container.cookie']

    core.container.cookie:
        class: CoreBundle\Container\CookieContainer

    core.factory.struct:
        class: CoreBundle\Factory\StructFactory

    core.factory.entity_formatter:
        class: CoreBundle\Factory\EntityFormatterFactory
        arguments:
            - @core.factory.entity
            - @doctrine.orm.entity_manager